### ISSUE TITLE
The way fixtures are loaded is untransparent

### ISSUE THREAD

**Issue by frankcorneliusmartin** [IKNL/vantage6-server#12]
The function `fixtures.load()` infers which nodes to create based on participations in a collaboration. This also means that API-keys are generated on the fly and cannot be set in advance.

I suggest moving to a fixture system that keeps a close relation to the database:

```yaml
Organization:
  - id: ...
    name: ...

User:
  - id: ...
    organization_id: ...
    username: ...
    password: ...
```

Loading fixtures can then be as easy as:

```python
def load_fixtures(fixtures):
    log.warn("Loading fixtures")

    session = Session()

    for clsname, values in fixtures.items():
        log.debug(f"  - Processing class {clsname}")
        cls = eval(clsname)

        for entry in values:
            instance = cls(**entry)
            session.add(instance)

    session.commit()
```

**Comment by jaspersnel** [comment]
I've looked into this solution and while it's very much possible, it makes writing the fixtures script extremely hard and error prone. One problem is you'd have to manually assign ID's to everything which would be very error-prone (and situational, depending on if the server's database has already been used). Also, many-many relationships need to be manually inserted in the intermediate tables, so you end up with situations like these for `Organization-Collaboration` and `User-Role-Rule`:

```YAML
User:
  - id: 1
    name: ...

Role:
  - id: 1
    name: ...

# map users and roles
Permission:
  - user_id: 1
    role_id: 1

# map rules and roles
role_rule_association:
  - role_id: 1
    rule_id: 45
  - role_id: 1
    rule_id: 14
 - ...
```

I think in an ideal world you'd have something in between the existing solution and this. Closer to the actual DB structure, but with the ability to simply refer to objects by (lists of) strings. This would obviously mean each class needs to be manually parsed in this `load` method.

e.g.

```YAML
User:
  - name: ...
    Roles: [ researcher, superuser ]

Role:
  - name: researcher
    Rules: [ ... ]
  -  name: superuser
    Rules: [ ... ]
```
